name: CI

on: 
  pull_request:
    branches: 
      - phrase-locales

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update encoding
      run: |
        iconv -f UTF-16 -t UTF-8 Localizable.strings -o Localizable.strings
    - name: commit change
      uses: alexesprit/action-update-file@master
      with:
        file-path: Localizable.strings
        commit-msg: commit change
        github-token: ${{ secrets.GITHUB_TOKEN }}
